# Generated by Django 3.1.1 on 2020-09-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(choices=[('H', 'Hangout'), ('M', 'Meal'), ('S', 'Special Occassion')], default='H', max_length=1)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.friend')),
            ],
        ),
    ]
