# Generated by Django 3.1.1 on 2020-09-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(verbose_name='Meeting Date'),
        ),
    ]
