# Generated by Django 3.1.1 on 2020-09-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200917_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='memories',
            field=models.ManyToManyField(to='main_app.Memory'),
        ),
    ]
